package com.example.nalassetmanagement.base


import com.example.nalassetmanagement.model.inventory.InventorySession
import com.example.nalassetmanagement.model.server.Asset
import com.example.nalassetmanagement.model.server.KeyValue
import com.example.nalassetmanagement.model.server.User
import com.example.nalassetmanagement.room.entity.InventorySessionStatus

fun getListInventorySessionFakeData() = mutableListOf(
    InventorySession(
        locationInventory = "Nal Kosmo",
        startDate = "01/07/2024",
        endDate = "02/07/2024",
        user = User(
            id = 1,
            userName = "nguyetnt1",
        ),
        status = InventorySessionStatus.END.value
    ),
    InventorySession(
        locationInventory = "Nal Thiên Hiền",
        startDate = "01/07/2024",
        endDate = "02/07/2024",
        user = User(
            id = 1,
            userName = "nguyetnt1",
        ),
        status = InventorySessionStatus.END.value
    ),
    InventorySession(
        locationInventory = "Nal Thiên Hiền",
        startDate = "02/06/2024",
        endDate = "04/06/2024",
        user = User(
            id = 1,
            userName = "nguyetnt1",
        ),
        status = InventorySessionStatus.IN_PROGRESS.value
    ),
    InventorySession(
        locationInventory = "Nal Thiên Hiền",
        startDate = "28/07/2024",
        endDate = "29/07/2024",
        user = User(
            id = 1,
            userName = "nguyetnt1",
        ),
        status = InventorySessionStatus.IN_PROGRESS.value
    ),
    InventorySession(
        locationInventory = "Nal Thiên Hiền",
        startDate = "28/07/2024",
        endDate = "29/07/2024",
        user = User(
            id = 1,
            userName = "nguyetnt1",
        ),
        status = InventorySessionStatus.IN_PROGRESS.value
    )
)

fun getAssetFakeData() = mutableListOf(
    Asset(
        id = 1,
        name = "Laptop",
        qrCode = "QR001",
        addressId = 101,
        statusId = 1,
        categoryId = 1,
        producerId = 1,
        modelId = 1,
        createdAt = "2024-01-01T10:00:00Z",
        updatedAt = "2024-01-02T10:00:00Z",
        deletedAt = null,
        userId = 1,
        category = KeyValue(id = 1, name = "Laptop"),
        address = KeyValue(id = 101, name = "Kosmo"),
        models = KeyValue(id = 201, name = "Model X"),
        producer = KeyValue(id = 301, name = "Apple"),
        status = KeyValue(id = 1, name = "Tệ"),
        user = User(
            id = 1,
            userName = "người dùng 1",
        ),
    ),
    Asset(
        id = 2,
        name = "Điện thoại",
        qrCode = "QR002",
        addressId = 102,
        statusId = 2,
        categoryId = 2,
        producerId = 2,
        modelId = 2,
        createdAt = "2024-01-02T11:00:00Z",
        updatedAt = "2024-01-03T11:00:00Z",
        deletedAt = null,
        userId = 2,
        category = KeyValue(id = 2, name = "Điện thoại"),
        address = KeyValue(id = 102, name = "Kosmo"),
        models = KeyValue(id = 202, name = "Model Y"),
        producer = KeyValue(id = 302, name = "Nhà sản xuất B"),
        status = KeyValue(id = 2, name = "Tốt"),
        user = User(
            id = 1,
            userName = "người dùng 1",
        ),
    ),
    Asset(
        id = 3,
        name = "Màn hình",
        qrCode = "QR003",
        addressId = 103,
        statusId = 3,
        categoryId = 3,
        producerId = 3,
        modelId = 3,
        createdAt = "2024-01-03T12:00:00Z",
        updatedAt = "2024-01-04T12:00:00Z",
        deletedAt = null,
        userId = 3,
        category = KeyValue(id = 3, name = "Màn hình"),
        address = KeyValue(id = 103, name = "Kosmo"),
        models = KeyValue(id = 203, name = "Model Z"),
        producer = KeyValue(id = 303, name = "Dell"),
        status = KeyValue(id = 3, name = "Tốt"),
        user = User(
            id = 3,
            userName = "người dùng 3",
        ),
    ),
    Asset(
        id = 4,
        name = "Bàn phím",
        qrCode = "QR004",
        addressId = 104,
        statusId = 1,
        categoryId = 4,
        producerId = 4,
        modelId = 4,
        createdAt = "2024-01-04T13:00:00Z",
        updatedAt = "2024-01-05T13:00:00Z",
        deletedAt = null,
        userId = 4,
        category = KeyValue(id = 4, name = "Bàn phím"),
        address = KeyValue(id = 104, name = "Kosmo"),
        models = KeyValue(id = 204, name = "Model A"),
        producer = KeyValue(id = 304, name = "Dell"),
        status = KeyValue(id = 1, name = "Tốt"),
        user = User(
            id = 4,
            userName = "người dùng 4",
        ),
    ),
    Asset(
        id = 30,
        name = "Chuột",
        qrCode = "QR005",
        addressId = 105,
        statusId = 2,
        categoryId = 5,
        producerId = 5,
        modelId = 5,
        createdAt = "2024-01-05T14:00:00Z",
        updatedAt = "2024-01-06T14:00:00Z",
        deletedAt = null,
        userId = 5,
        category = KeyValue(id = 5, name = "Chuột"),
        address = KeyValue(id = 105, name = "Kosmo"),
        models = KeyValue(id = 205, name = "Model B"),
        producer = KeyValue(id = 305, name = "Nhà sản xuất E"),
        status = KeyValue(id = 2, name = "Tốt"),
        user = User(
            id = 5,
            userName = "người dùng 5",
        ),
    ),
    Asset(
        id = 5,
        name = "Laptop",
        qrCode = "QR006",
        addressId = 106,
        statusId = 1,
        categoryId = 1,
        producerId = 6,
        modelId = 6,
        createdAt = "2024-01-06T15:00:00Z",
        updatedAt = "2024-01-07T15:00:00Z",
        deletedAt = null,
        userId = 6,
        category = KeyValue(id = 1, name = "Laptop"),
        address = KeyValue(id = 106, name = "Kosmo"),
        models = KeyValue(id = 206, name = "Model C"),
        producer = KeyValue(id = 306, name = "Apple"),
        status = KeyValue(id = 1, name = "Tệ"),
        user = User(id = 6, userName = "Người dùng 6")
    ),
    Asset(
        id = 6,
        name = "Điện thoại",
        qrCode = "QR007",
        addressId = 107,
        statusId = 3,
        categoryId = 2,
        producerId = 7,
        modelId = 7,
        createdAt = "2024-01-07T16:00:00Z",
        updatedAt = "2024-01-08T16:00:00Z",
        deletedAt = null,
        userId = 7,
        category = KeyValue(id = 2, name = "Điện thoại"),
        address = KeyValue(id = 107, name = "Kosmo"),
        models = KeyValue(id = 207, name = "Model D"),
        producer = KeyValue(id = 307, name = "Apple"),
        status = KeyValue(id = 3, name = "Tệ"),
        user = User(id = 7, userName = "Người dùng 7")
    ),
    Asset(
        id = 7,
        name = "Màn hình",
        qrCode = "QR008",
        addressId = 108,
        statusId = 2,
        categoryId = 3,
        producerId = 8,
        modelId = 8,
        createdAt = "2024-01-08T17:00:00Z",
        updatedAt = "2024-01-09T17:00:00Z",
        deletedAt = null,
        userId = 8,
        category = KeyValue(id = 3, name = "Màn hình"),
        address = KeyValue(id = 108, name = "Phòng 108"),
        models = KeyValue(id = 208, name = "Model E"),
        producer = KeyValue(id = 308, name = "Dell"),
        status = KeyValue(id = 2, name = "Tốt"),
        user = User(id = 8, userName = "Người dùng 8")
    ),
    Asset(
        id = 8,
        name = "Laptop",
        qrCode = "QR006",
        addressId = 106,
        statusId = 1,
        categoryId = 1,
        producerId = 6,
        modelId = 6,
        createdAt = "2024-01-06T15:00:00Z",
        updatedAt = "2024-01-07T15:00:00Z",
        deletedAt = null,
        userId = 6,
        category = KeyValue(id = 1, name = "Laptop"),
        address = KeyValue(id = 106, name = "Kosmo"),
        models = KeyValue(id = 206, name = "Model C"),
        producer = KeyValue(id = 306, name = "Apple"),
        status = KeyValue(id = 1, name = "Tệ"),
        user = User(id = 6, userName = "Người dùng 6")
    ),
    Asset(
        id = 9,
        name = "Chuột",
        qrCode = "QR010",
        addressId = 110,
        statusId = 1,
        categoryId = 5,
        producerId = 10,
        modelId = 10,
        createdAt = "2024-01-10T19:00:00Z",
        updatedAt = "2024-01-11T19:00:00Z",
        deletedAt = null,
        userId = 10,
        category = KeyValue(id = 5, name = "Chuột"),
        address = KeyValue(id = 110, name = "Nal building"),
        models = KeyValue(id = 210, name = "Model G"),
        producer = KeyValue(id = 310, name = "Dell"),
        status = KeyValue(id = 1, name = "Tốt"),
        user = User(id = 10, userName = "Người dùng 10")
    ),
    Asset(
        id = 10,
        name = "Máy tính",
        qrCode = "QR011",
        addressId = 111,
        statusId = 2,
        categoryId = 1,
        producerId = 11,
        modelId = 11,
        createdAt = "2024-01-11T20:00:00Z",
        updatedAt = "2024-01-12T20:00:00Z",
        deletedAt = null,
        userId = 11,
        category = KeyValue(id = 1, name = "Máy tính"),
        address = KeyValue(id = 111, name = "Nal building"),
        models = KeyValue(id = 211, name = "Model H"),
        producer = KeyValue(id = 311, name = "Apple"),
        status = KeyValue(id = 2, name = "Tốt"),
        user = User(id = 11, userName = "Người dùng 11")
    ),
    Asset(
        id = 11,
        name = "Điện thoại",
        qrCode = "QR012",
        addressId = 112,
        statusId = 3,
        categoryId = 2,
        producerId = 12,
        modelId = 12,
        createdAt = "2024-01-12T21:00:00Z",
        updatedAt = "2024-01-13T21:00:00Z",
        deletedAt = null,
        userId = 12,
        category = KeyValue(id = 2, name = "Điện thoại"),
        address = KeyValue(id = 112, name = "Nal Building"),
        models = KeyValue(id = 212, name = "Model I"),
        producer = KeyValue(id = 312, name = "Apple"),
        status = KeyValue(id = 3, name = "Bình thường"),
        user = User(id = 12, userName = "Người dùng 12")
    ),
    Asset(
        id = 12,
        name = "Màn hình",
        qrCode = "QR013",
        addressId = 113,
        statusId = 1,
        categoryId = 3,
        producerId = 13,
        modelId = 13,
        createdAt = "2024-01-13T22:00:00Z",
        updatedAt = "2024-01-14T22:00:00Z",
        deletedAt = null,
        userId = 13,
        category = KeyValue(id = 3, name = "Màn hình"),
        address = KeyValue(id = 113, name = "Phòng 113"),
        models = KeyValue(id = 213, name = "Model J"),
        producer = KeyValue(id = 313, name = "Dell"),
        status = KeyValue(id = 1, name = "Tốt"),
        user = User(id = 13, userName = "Người dùng 13")
    ),
    Asset(
        id = 13,
        name = "Bàn phím",
        qrCode = "QR014",
        addressId = 114,
        statusId = 2,
        categoryId = 4,
        producerId = 14,
        modelId = 14,
        createdAt = "2024-01-14T23:00:00Z",
        updatedAt = "2024-01-15T23:00:00Z",
        deletedAt = null,
        userId = 14,
        category = KeyValue(id = 4, name = "Bàn phím"),
        address = KeyValue(id = 114, name = "Phòng 114"),
        models = KeyValue(id = 214, name = "Model K"),
        producer = KeyValue(id = 314, name = "Dell"),
        status = KeyValue(id = 2, name = "Bình thường"),
        user = User(id = 14, userName = "vietbq")
    ),
    Asset(
        id = 14,
        name = "Chuột",
        qrCode = "QR015",
        addressId = 115,
        statusId = 3,
        categoryId = 5,
        producerId = 15,
        modelId = 15,
        createdAt = "2024-01-15T00:00:00Z",
        updatedAt = "2024-01-16T00:00:00Z",
        deletedAt = null,
        userId = 15,
        category = KeyValue(id = 5, name = "Chuột"),
        address = KeyValue(id = 115, name = "Phòng 115"),
        models = KeyValue(id = 215, name = "Model L"),
        producer = KeyValue(id = 315, name = "Dell"),
        status = KeyValue(id = 3, name = "Tệ"),
        user = User(id = 15, userName = "minhnv1")
    ),
    Asset(
        id = 15,
        name = "Laptop",
        qrCode = "QR016",
        addressId = 116,
        statusId = 1,
        categoryId = 1,
        producerId = 16,
        modelId = 16,
        createdAt = "2024-01-16T01:00:00Z",
        updatedAt = "2024-01-17T01:00:00Z",
        deletedAt = null,
        userId = 16,
        category = KeyValue(id = 1, name = "Máy tính"),
        address = KeyValue(id = 116, name = "Phòng 116"),
        models = KeyValue(id = 216, name = "Model M"),
        producer = KeyValue(id = 316, name = "Apple"),
        status = KeyValue(id = 1, name = "Bình thường"),
        user = User(id = 16, userName = "thaott")
    ),
    Asset(
        id = 16,
        name = "Điện thoại",
        qrCode = "QR017",
        addressId = 117,
        statusId = 2,
        categoryId = 2,
        producerId = 17,
        modelId = 17,
        createdAt = "2024-01-17T02:00:00Z",
        updatedAt = "2024-01-18T02:00:00Z",
        deletedAt = null,
        userId = 17,
        category = KeyValue(id = 2, name = "Điện thoại"),
        address = KeyValue(id = 117, name = "Phòng 117"),
        models = KeyValue(id = 217, name = "Model N"),
        producer = KeyValue(id = 317, name = "Samsung"),
        status = KeyValue(id = 2, name = "Bình thường"),
        user = User(id = 17, userName = "thaott")
    ),
    Asset(
        id = 17,
        name = "Màn hình",
        qrCode = "QR018",
        addressId = 118,
        statusId = 3,
        categoryId = 3,
        producerId = 18,
        modelId = 18,
        createdAt = "2024-01-18T03:00:00Z",
        updatedAt = "2024-01-19T03:00:00Z",
        deletedAt = null,
        userId = 18,
        category = KeyValue(id = 3, name = "Màn hình"),
        address = KeyValue(id = 118, name = "Phòng 118"),
        models = KeyValue(id = 218, name = "Model O"),
        producer = KeyValue(id = 318, name = "Dell"),
        status = KeyValue(id = 3, name = "Bình thường"),
        user = User(id = 18, userName = "nguyetdta")
    ),
    Asset(
        id = 18,
        name = "bàn phím",
        qrCode = "QR019",
        addressId = 119,
        statusId = 1,
        categoryId = 4,
        producerId = 19,
        modelId = 19,
        createdAt = "2024-01-19T04:00:00Z",
        updatedAt = "2024-01-20T04:00:00Z",
        deletedAt = null,
        userId = 19,
        category = KeyValue(id = 4, name = "Bàn phím"),
        address = KeyValue(id = 119, name = "Phòng 119"),
        models = KeyValue(id = 219, name = "Model P"),
        producer = KeyValue(id = 319, name = "Apple"),
        status = KeyValue(id = 1, name = "Tệ"),
        user = User(id = 19, userName = "nguyetdta")
    ),
    Asset(
        id = 19,
        name = "chuột",
        qrCode = "QR020",
        addressId = 120,
        statusId = 2,
        categoryId = 5,
        producerId = 20,
        modelId = 20,
        createdAt = "2024-01-20T05:00:00Z",
        updatedAt = "2024-01-21T05:00:00Z",
        deletedAt = null,
        userId = 20,
        category = KeyValue(id = 5, name = "Chuột"),
        address = KeyValue(id = 120, name = "Phòng 120"),
        models = KeyValue(id = 220, name = "Model Q"),
        producer = KeyValue(id = 320, name = "Apple"),
        status = KeyValue(id = 2, name = "Tốt"),
        user = User(id = 20, userName = "nguyetdta")
    )
)


