package com.example.nalassetmanagement.base

import com.example.nalassetmanagement.model.Asset
import com.example.nalassetmanagement.model.KeyValue
import com.example.nalassetmanagement.model.inventory.InventorySession
import com.example.nalassetmanagement.room.entity.InventorySessionStatus

fun getListInventorySessionFakeData() = mutableListOf(
    InventorySession(
        locationInventory = "Nal Kosmo",
        startDate = "01/07/2024",
        endDate = "02/07/2024",
        user = KeyValue(
            id = 1,
            name = "nguyetnt1",
        ),
        status = InventorySessionStatus.END.value
    ),
    InventorySession(
        locationInventory = "Nal Thiên Hiền",
        startDate = "01/07/2024",
        endDate = "02/07/2024",
        user = KeyValue(
            id = 1,
            name = "nguyetnt1",
        ),
        status = InventorySessionStatus.END.value
    ),
    InventorySession(
        locationInventory = "Nal Thiên Hiền",
        startDate = "02/06/2024",
        endDate = "04/06/2024",
        user = KeyValue(
            id = 1,
            name = "nguyetnt1",
        ),
        status = InventorySessionStatus.IN_PROGRESS.value
    ),
    InventorySession(
        locationInventory = "Nal Thiên Hiền",
        startDate = "28/07/2024",
        endDate = "29/07/2024",
        user = KeyValue(
            id = 1,
            name = "nguyetnt1",
        ),
        status = InventorySessionStatus.IN_PROGRESS.value
    ),
    InventorySession(
        locationInventory = "Nal Thiên Hiền",
        startDate = "28/07/2024",
        endDate = "29/07/2024",
        user = KeyValue(
            id = 1,
            name = "nguyetnt1",
        ),
        status = InventorySessionStatus.IN_PROGRESS.value
    )
)

fun getAssetFakeData() = mutableListOf(
    Asset(
        id = "1",
        name = "máy tính",
        qrCode = "QR001",
        addressId = 101,
        statusId = 1,
        categoryId = 1,
        producerId = 1,
        modelId = 1,
        createdAt = "2024-01-01T10:00:00Z",
        updatedAt = "2024-01-02T10:00:00Z",
        deletedAt = null,
        userId = 1,
        category = KeyValue(id = 1, name = "Máy tính"),
        address = KeyValue(id = 101, name = "Phòng 101"),
        models = KeyValue(id = 201, name = "Model X"),
        producer = KeyValue(id = 301, name = "Nhà sản xuất A"),
        status = KeyValue(id = 1, name = "Sẵn sàng"),
        user = KeyValue(id = 1, name = "Người dùng 1")
    ),
    Asset(
        id = "2",
        name = "điện thoại",
        qrCode = "QR002",
        addressId = 102,
        statusId = 2,
        categoryId = 2,
        producerId = 2,
        modelId = 2,
        createdAt = "2024-01-02T11:00:00Z",
        updatedAt = "2024-01-03T11:00:00Z",
        deletedAt = null,
        userId = 2,
        category = KeyValue(id = 2, name = "Điện thoại"),
        address = KeyValue(id = 102, name = "Phòng 102"),
        models = KeyValue(id = 202, name = "Model Y"),
        producer = KeyValue(id = 302, name = "Nhà sản xuất B"),
        status = KeyValue(id = 2, name = "Đang sử dụng"),
        user = KeyValue(id = 2, name = "Người dùng 2")
    ),
    Asset(
        id = "3",
        name = "màn hình",
        qrCode = "QR003",
        addressId = 103,
        statusId = 3,
        categoryId = 3,
        producerId = 3,
        modelId = 3,
        createdAt = "2024-01-03T12:00:00Z",
        updatedAt = "2024-01-04T12:00:00Z",
        deletedAt = null,
        userId = 3,
        category = KeyValue(id = 3, name = "Màn hình"),
        address = KeyValue(id = 103, name = "Phòng 103"),
        models = KeyValue(id = 203, name = "Model Z"),
        producer = KeyValue(id = 303, name = "Nhà sản xuất C"),
        status = KeyValue(id = 3, name = "Bảo trì"),
        user = KeyValue(id = 3, name = "Người dùng 3")
    ),
    Asset(
        id = "4",
        name = "bàn phím",
        qrCode = "QR004",
        addressId = 104,
        statusId = 1,
        categoryId = 4,
        producerId = 4,
        modelId = 4,
        createdAt = "2024-01-04T13:00:00Z",
        updatedAt = "2024-01-05T13:00:00Z",
        deletedAt = null,
        userId = 4,
        category = KeyValue(id = 4, name = "Bàn phím"),
        address = KeyValue(id = 104, name = "Phòng 104"),
        models = KeyValue(id = 204, name = "Model A"),
        producer = KeyValue(id = 304, name = "Nhà sản xuất D"),
        status = KeyValue(id = 1, name = "Sẵn sàng"),
        user = KeyValue(id = 4, name = "Người dùng 4")
    ),
    Asset(
        id = "5",
        name = "chuột",
        qrCode = "QR005",
        addressId = 105,
        statusId = 2,
        categoryId = 5,
        producerId = 5,
        modelId = 5,
        createdAt = "2024-01-05T14:00:00Z",
        updatedAt = "2024-01-06T14:00:00Z",
        deletedAt = null,
        userId = 5,
        category = KeyValue(id = 5, name = "Chuột"),
        address = KeyValue(id = 105, name = "Phòng 105"),
        models = KeyValue(id = 205, name = "Model B"),
        producer = KeyValue(id = 305, name = "Nhà sản xuất E"),
        status = KeyValue(id = 2, name = "Đang sử dụng"),
        user = KeyValue(id = 5, name = "Người dùng 5")
    ),
    Asset(
        id = "6",
        name = "máy tính",
        qrCode = "QR006",
        addressId = 106,
        statusId = 1,
        categoryId = 1,
        producerId = 6,
        modelId = 6,
        createdAt = "2024-01-06T15:00:00Z",
        updatedAt = "2024-01-07T15:00:00Z",
        deletedAt = null,
        userId = 6,
        category = KeyValue(id = 1, name = "Máy tính"),
        address = KeyValue(id = 106, name = "Phòng 106"),
        models = KeyValue(id = 206, name = "Model C"),
        producer = KeyValue(id = 306, name = "Nhà sản xuất F"),
        status = KeyValue(id = 1, name = "Sẵn sàng"),
        user = KeyValue(id = 6, name = "Người dùng 6")
    ),
    Asset(
        id = "7",
        name = "điện thoại",
        qrCode = "QR007",
        addressId = 107,
        statusId = 3,
        categoryId = 2,
        producerId = 7,
        modelId = 7,
        createdAt = "2024-01-07T16:00:00Z",
        updatedAt = "2024-01-08T16:00:00Z",
        deletedAt = null,
        userId = 7,
        category = KeyValue(id = 2, name = "Điện thoại"),
        address = KeyValue(id = 107, name = "Phòng 107"),
        models = KeyValue(id = 207, name = "Model D"),
        producer = KeyValue(id = 307, name = "Nhà sản xuất G"),
        status = KeyValue(id = 3, name = "Bảo trì"),
        user = KeyValue(id = 7, name = "Người dùng 7")
    ),
    Asset(
        id = "8",
        name = "màn hình",
        qrCode = "QR008",
        addressId = 108,
        statusId = 2,
        categoryId = 3,
        producerId = 8,
        modelId = 8,
        createdAt = "2024-01-08T17:00:00Z",
        updatedAt = "2024-01-09T17:00:00Z",
        deletedAt = null,
        userId = 8,
        category = KeyValue(id = 3, name = "Màn hình"),
        address = KeyValue(id = 108, name = "Phòng 108"),
        models = KeyValue(id = 208, name = "Model E"),
        producer = KeyValue(id = 308, name = "Nhà sản xuất H"),
        status = KeyValue(id = 2, name = "Đang sử dụng"),
        user = KeyValue(id = 8, name = "Người dùng 8")
    ),
    Asset(
        id = "9",
        name = "bàn phím",
        qrCode = "QR009",
        addressId = 109,
        statusId = 1,
        categoryId = 4,
        producerId = 9,
        modelId = 9,
        createdAt = "2024-01-09T18:00:00Z",
        updatedAt = "2024-01-10T18:00:00Z",
        deletedAt = null,
        userId = 9,
        category = KeyValue(id = 4, name = "Bàn phím"),
        address = KeyValue(id = 109, name = "Phòng 109"),
        models = KeyValue(id = 209, name = "Model F"),
        producer = KeyValue(id = 309, name = "Nhà sản xuất I"),
        status = KeyValue(id = 1, name = "Sẵn sàng"),
        user = KeyValue(id = 9, name = "Người dùng 9")
    ),
    Asset(
        id = "10",
        name = "chuột",
        qrCode = "QR010",
        addressId = 110,
        statusId = 1,
        categoryId = 5,
        producerId = 10,
        modelId = 10,
        createdAt = "2024-01-10T19:00:00Z",
        updatedAt = "2024-01-11T19:00:00Z",
        deletedAt = null,
        userId = 10,
        category = KeyValue(id = 5, name = "Chuột"),
        address = KeyValue(id = 110, name = "Phòng 110"),
        models = KeyValue(id = 210, name = "Model G"),
        producer = KeyValue(id = 310, name = "Nhà sản xuất J"),
        status = KeyValue(id = 1, name = "Sẵn sàng"),
        user = KeyValue(id = 10, name = "Người dùng 10")
    ),
    Asset(
        id = "11",
        name = "máy tính",
        qrCode = "QR011",
        addressId = 111,
        statusId = 2,
        categoryId = 1,
        producerId = 11,
        modelId = 11,
        createdAt = "2024-01-11T20:00:00Z",
        updatedAt = "2024-01-12T20:00:00Z",
        deletedAt = null,
        userId = 11,
        category = KeyValue(id = 1, name = "Máy tính"),
        address = KeyValue(id = 111, name = "Phòng 111"),
        models = KeyValue(id = 211, name = "Model H"),
        producer = KeyValue(id = 311, name = "Nhà sản xuất K"),
        status = KeyValue(id = 2, name = "Đang sử dụng"),
        user = KeyValue(id = 11, name = "Người dùng 11")
    ),
    Asset(
        id = "12",
        name = "điện thoại",
        qrCode = "QR012",
        addressId = 112,
        statusId = 3,
        categoryId = 2,
        producerId = 12,
        modelId = 12,
        createdAt = "2024-01-12T21:00:00Z",
        updatedAt = "2024-01-13T21:00:00Z",
        deletedAt = null,
        userId = 12,
        category = KeyValue(id = 2, name = "Điện thoại"),
        address = KeyValue(id = 112, name = "Phòng 112"),
        models = KeyValue(id = 212, name = "Model I"),
        producer = KeyValue(id = 312, name = "Nhà sản xuất L"),
        status = KeyValue(id = 3, name = "Bảo trì"),
        user = KeyValue(id = 12, name = "Người dùng 12")
    ),
    Asset(
        id = "13",
        name = "màn hình",
        qrCode = "QR013",
        addressId = 113,
        statusId = 1,
        categoryId = 3,
        producerId = 13,
        modelId = 13,
        createdAt = "2024-01-13T22:00:00Z",
        updatedAt = "2024-01-14T22:00:00Z",
        deletedAt = null,
        userId = 13,
        category = KeyValue(id = 3, name = "Màn hình"),
        address = KeyValue(id = 113, name = "Phòng 113"),
        models = KeyValue(id = 213, name = "Model J"),
        producer = KeyValue(id = 313, name = "Nhà sản xuất M"),
        status = KeyValue(id = 1, name = "Sẵn sàng"),
        user = KeyValue(id = 13, name = "Người dùng 13")
    ),
    Asset(
        id = "14",
        name = "bàn phím",
        qrCode = "QR014",
        addressId = 114,
        statusId = 2,
        categoryId = 4,
        producerId = 14,
        modelId = 14,
        createdAt = "2024-01-14T23:00:00Z",
        updatedAt = "2024-01-15T23:00:00Z",
        deletedAt = null,
        userId = 14,
        category = KeyValue(id = 4, name = "Bàn phím"),
        address = KeyValue(id = 114, name = "Phòng 114"),
        models = KeyValue(id = 214, name = "Model K"),
        producer = KeyValue(id = 314, name = "Nhà sản xuất N"),
        status = KeyValue(id = 2, name = "Đang sử dụng"),
        user = KeyValue(id = 14, name = "vietbq")
    ),
    Asset(
        id = "15",
        name = "chuột",
        qrCode = "QR015",
        addressId = 115,
        statusId = 3,
        categoryId = 5,
        producerId = 15,
        modelId = 15,
        createdAt = "2024-01-15T00:00:00Z",
        updatedAt = "2024-01-16T00:00:00Z",
        deletedAt = null,
        userId = 15,
        category = KeyValue(id = 5, name = "Chuột"),
        address = KeyValue(id = 115, name = "Phòng 115"),
        models = KeyValue(id = 215, name = "Model L"),
        producer = KeyValue(id = 315, name = "Nhà sản xuất O"),
        status = KeyValue(id = 3, name = "Bảo trì"),
        user = KeyValue(id = 15, name = "minhnv1")
    ),
    Asset(
        id = "16",
        name = "máy tính",
        qrCode = "QR016",
        addressId = 116,
        statusId = 1,
        categoryId = 1,
        producerId = 16,
        modelId = 16,
        createdAt = "2024-01-16T01:00:00Z",
        updatedAt = "2024-01-17T01:00:00Z",
        deletedAt = null,
        userId = 16,
        category = KeyValue(id = 1, name = "Máy tính"),
        address = KeyValue(id = 116, name = "Phòng 116"),
        models = KeyValue(id = 216, name = "Model M"),
        producer = KeyValue(id = 316, name = "Nhà sản xuất P"),
        status = KeyValue(id = 1, name = "Sẵn sàng"),
        user = KeyValue(id = 16, name = "thaott")
    ),
    Asset(
        id = "17",
        name = "điện thoại",
        qrCode = "QR017",
        addressId = 117,
        statusId = 2,
        categoryId = 2,
        producerId = 17,
        modelId = 17,
        createdAt = "2024-01-17T02:00:00Z",
        updatedAt = "2024-01-18T02:00:00Z",
        deletedAt = null,
        userId = 17,
        category = KeyValue(id = 2, name = "Điện thoại"),
        address = KeyValue(id = 117, name = "Phòng 117"),
        models = KeyValue(id = 217, name = "Model N"),
        producer = KeyValue(id = 317, name = "Nhà sản xuất Q"),
        status = KeyValue(id = 2, name = "Đang sử dụng"),
        user = KeyValue(id = 17, name = "thaott")
    ),
    Asset(
        id = "18",
        name = "màn hình",
        qrCode = "QR018",
        addressId = 118,
        statusId = 3,
        categoryId = 3,
        producerId = 18,
        modelId = 18,
        createdAt = "2024-01-18T03:00:00Z",
        updatedAt = "2024-01-19T03:00:00Z",
        deletedAt = null,
        userId = 18,
        category = KeyValue(id = 3, name = "Màn hình"),
        address = KeyValue(id = 118, name = "Phòng 118"),
        models = KeyValue(id = 218, name = "Model O"),
        producer = KeyValue(id = 318, name = "Nhà sản xuất R"),
        status = KeyValue(id = 3, name = "Bảo trì"),
        user = KeyValue(id = 18, name = "nguyetdta")
    ),
    Asset(
        id = "19",
        name = "bàn phím",
        qrCode = "QR019",
        addressId = 119,
        statusId = 1,
        categoryId = 4,
        producerId = 19,
        modelId = 19,
        createdAt = "2024-01-19T04:00:00Z",
        updatedAt = "2024-01-20T04:00:00Z",
        deletedAt = null,
        userId = 19,
        category = KeyValue(id = 4, name = "Bàn phím"),
        address = KeyValue(id = 119, name = "Phòng 119"),
        models = KeyValue(id = 219, name = "Model P"),
        producer = KeyValue(id = 319, name = "Nhà sản xuất S"),
        status = KeyValue(id = 1, name = "Sẵn sàng"),
        user = KeyValue(id = 19, name = "nguyetdta")
    ),
    Asset(
        id = "20",
        name = "chuột",
        qrCode = "QR020",
        addressId = 120,
        statusId = 2,
        categoryId = 5,
        producerId = 20,
        modelId = 20,
        createdAt = "2024-01-20T05:00:00Z",
        updatedAt = "2024-01-21T05:00:00Z",
        deletedAt = null,
        userId = 20,
        category = KeyValue(id = 5, name = "Chuột"),
        address = KeyValue(id = 120, name = "Phòng 120"),
        models = KeyValue(id = 220, name = "Model Q"),
        producer = KeyValue(id = 320, name = "Nhà sản xuất T"),
        status = KeyValue(id = 2, name = "Đang sử dụng"),
        user = KeyValue(id = 20, name = "nguyetdta")
    ),
    Asset(
        id = "21",
        name = "máy tính",
        qrCode = "QR021",
        addressId = 121,
        statusId = 3,
        categoryId = 1,
        producerId = 21,
        modelId = 21,
        createdAt = "2024-01-21T06:00:00Z",
        updatedAt = "2024-01-22T06:00:00Z",
        deletedAt = null,
        userId = 21,
        category = KeyValue(id = 1, name = "Máy tính"),
        address = KeyValue(id = 121, name = "Phòng 121"),
        models = KeyValue(id = 221, name = "Model R"),
        producer = KeyValue(id = 321, name = "Nhà sản xuất U"),
        status = KeyValue(id = 3, name = "Bảo trì"),
        user = KeyValue(id = 21, name = "cuongnm1")
    ),
    Asset(
        id = "22",
        name = "điện thoại",
        qrCode = "QR022",
        addressId = 122,
        statusId = 1,
        categoryId = 2,
        producerId = 22,
        modelId = 22,
        createdAt = "2024-01-22T07:00:00Z",
        updatedAt = "2024-01-23T07:00:00Z",
        deletedAt = null,
        userId = 22,
        category = KeyValue(id = 2, name = "Điện thoại"),
        address = KeyValue(id = 122, name = "Phòng 122"),
        models = KeyValue(id = 222, name = "Model S"),
        producer = KeyValue(id = 322, name = "Nhà sản xuất V"),
        status = KeyValue(id = 1, name = "Sẵn sàng"),
        user = KeyValue(id = 22, name = "vietbq")
    ),
    Asset(
        id = "23",
        name = "màn hình",
        qrCode = "QR023",
        addressId = 123,
        statusId = 2,
        categoryId = 3,
        producerId = 23,
        modelId = 23,
        createdAt = "2024-01-23T08:00:00Z",
        updatedAt = "2024-01-24T08:00:00Z",
        deletedAt = null,
        userId = 23,
        category = KeyValue(id = 3, name = "Màn hình"),
        address = KeyValue(id = 123, name = "Phòng 123"),
        models = KeyValue(id = 223, name = "Model T"),
        producer = KeyValue(id = 323, name = "Nhà sản xuất W"),
        status = KeyValue(id = 2, name = "Đang sử dụng"),
        user = KeyValue(id = 23, name = "vietbq")
    ),
    Asset(
        id = "24",
        name = "bàn phím",
        qrCode = "QR024",
        addressId = 124,
        statusId = 3,
        categoryId = 4,
        producerId = 24,
        modelId = 24,
        createdAt = "2024-01-24T09:00:00Z",
        updatedAt = "2024-01-25T09:00:00Z",
        deletedAt = null,
        userId = 24,
        category = KeyValue(id = 4, name = "Bàn phím"),
        address = KeyValue(id = 124, name = "Phòng 124"),
        models = KeyValue(id = 224, name = "Model U"),
        producer = KeyValue(id = 324, name = "Nhà sản xuất X"),
        status = KeyValue(id = 3, name = "Bảo trì"),
        user = KeyValue(id = 24, name = "vietbp")
    ),
    Asset(
        id = "25",
        name = "chuột",
        qrCode = "QR025",
        addressId = 125,
        statusId = 1,
        categoryId = 5,
        producerId = 25,
        modelId = 25,
        createdAt = "2024-01-25T10:00:00Z",
        updatedAt = "2024-01-26T10:00:00Z",
        deletedAt = null,
        userId = 25,
        category = KeyValue(id = 5, name = "Chuột"),
        address = KeyValue(id = 125, name = "Phòng 125"),
        models = KeyValue(id = 225, name = "Model V"),
        producer = KeyValue(id = 325, name = "Nhà sản xuất Y"),
        status = KeyValue(id = 1, name = "Sẵn sàng"),
        user = KeyValue(id = 25, name = "vietbp")
    ),
    Asset(
        id = "26",
        name = "máy tính",
        qrCode = "QR026",
        addressId = 126,
        statusId = 2,
        categoryId = 1,
        producerId = 26,
        modelId = 26,
        createdAt = "2024-01-26T11:00:00Z",
        updatedAt = "2024-01-27T11:00:00Z",
        deletedAt = null,
        userId = 26,
        category = KeyValue(id = 1, name = "Máy tính"),
        address = KeyValue(id = 126, name = "Phòng 126"),
        models = KeyValue(id = 226, name = "Model W"),
        producer = KeyValue(id = 326, name = "Nhà sản xuất Z"),
        status = KeyValue(id = 2, name = "Đang sử dụng"),
        user = KeyValue(id = 26, name = "vietvv")
    ),
    Asset(
        id = "27",
        name = "điện thoại",
        qrCode = "QR027",
        addressId = 127,
        statusId = 3,
        categoryId = 2,
        producerId = 27,
        modelId = 27,
        createdAt = "2024-01-27T12:00:00Z",
        updatedAt = "2024-01-28T12:00:00Z",
        deletedAt = null,
        userId = 27,
        category = KeyValue(id = 2, name = "Điện thoại"),
        address = KeyValue(id = 127, name = "Phòng 127"),
        models = KeyValue(id = 227, name = "Model X"),
        producer = KeyValue(id = 327, name = "Nhà sản xuất A1"),
        status = KeyValue(id = 3, name = "Bảo trì"),
        user = KeyValue(id = 27, name = "tungbp")
    ),
    Asset(
        id = "28",
        name = "màn hình",
        qrCode = "QR028",
        addressId = 128,
        statusId = 1,
        categoryId = 3,
        producerId = 28,
        modelId = 28,
        createdAt = "2024-01-28T13:00:00Z",
        updatedAt = "2024-01-29T13:00:00Z",
        deletedAt = null,
        userId = 28,
        category = KeyValue(id = 3, name = "Màn hình"),
        address = KeyValue(id = 128, name = "Phòng 128"),
        models = KeyValue(id = 228, name = "Model Y"),
        producer = KeyValue(id = 328, name = "Nhà sản xuất B1"),
        status = KeyValue(id = 1, name = "Sẵn sàng"),
        user = KeyValue(id = 28, name = "thaott")
    ),
    Asset(
        id = "29",
        name = "bàn phím",
        qrCode = "QR029",
        addressId = 129,
        statusId = 2,
        categoryId = 4,
        producerId = 29,
        modelId = 29,
        createdAt = "2024-01-29T14:00:00Z",
        updatedAt = "2024-01-30T14:00:00Z",
        deletedAt = null,
        userId = 29,
        category = KeyValue(id = 4, name = "Bàn phím"),
        address = KeyValue(id = 129, name = "Phòng 129"),
        models = KeyValue(id = 229, name = "Model Z"),
        producer = KeyValue(id = 329, name = "Nhà sản xuất C1"),
        status = KeyValue(id = 2, name = "Đang sử dụng"),
        user = KeyValue(id = 29, name = "minhnv")
    ),
    Asset(
        id = "30",
        name = "chuột",
        qrCode = "QR030",
        addressId = 130,
        statusId = 3,
        categoryId = 5,
        producerId = 30,
        modelId = 30,
        createdAt = "2024-01-30T15:00:00Z",
        updatedAt = "2024-01-31T15:00:00Z",
        deletedAt = null,
        userId = 30,
        category = KeyValue(id = 5, name = "Chuột"),
        address = KeyValue(id = 130, name = "Phòng 130"),
        models = KeyValue(id = 230, name = "Model A2"),
        producer = KeyValue(id = 330, name = "Nhà sản xuất D1"),
        status = KeyValue(id = 3, name = "Bảo trì"),
        user = KeyValue(id = 30, name = "cuongnm1")
    )
)


