name: Android CI

env:
  # The name of the main module repository
  main_project_module: app

  # The name version
  version: v820
  # The name task
  name_task: issue1726_add_mitene_funtion

on:
  push:
    branches:
      - dungnb

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Run Tests Build
      - name: Run gradle tests
        run: ./gradlew test
        
      # Run Build Project
      - name: Build with Gradle
        run: ./gradlew build

      # Create APK Debug
      - name: Build apk debug project (APK)
        run: ./gradlew assembleDebug

      # Upload Artifact Build
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{version}} - ${{ env.name_task }}.apk
          path: app/build/outputs/apk/debug/${{ env.date_today }} - ${{version}} - ${{ env.name_task }}.apk
